name: PowerShell Hello World

on:
  workflow_dispatch:
    inputs:
      inputs-json:
        description: JSON payload containing all necessary inputs as key/value pairs.
        required: true
        type: string
        default: '{"adGroupsCreationEnvironment": "TEST", "adGroupNames": ["adGroup1"]}'
      run-name:
        description: The desired name for the workflow run
        required: true
        default: 'HarbourFlowName-GUID'
      output-job-name:
        description: The name of the job that writes the output of the workflow run to the console.
        required: true
        default: 'output-job-GUID'
      json-response-key:
        description: The key used to log the JSON response by the output job in the console.
        required: true
        default: 'json-response'
  push:

jobs:
  say-hello:
    runs-on: [self-hosted, windows, harbour] # You can also use windows-latest
    steps:
      - name: Run PowerShell script
        run: |
          Write-Host "Hello World from PowerShell!"
          $version = $PSVersionTable.PSVersion
          Write-Host "Running on PowerShell version: $version"
